apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: logging
data:
  logstash.conf: |-
    input {
      http {
        port      => 8080
      }
    }
    filter {
      prune {
        blacklist_values => {
          "kubernetes.annotations.prometheus_io/path" => "/api/v1/metrics/prometheus"
        }
      }
    }
    output {
      loggly {
        key => "f5087cf4-d749-41c1-8b7f-484661292d08"
        tag => "logstash,kubernetes"
        host => "logs-01.loggly.com"
        proto => "http"
      }
    }
