apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: logging
spec:
  type: NodePort
  selector:
    role: hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
