apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring-v2
data:
  alertmanager.yml: |-
    global:
      http_config:
        tls_config:
          insecure_skip_verify: true
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/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'
  
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      # A default receiver
      receiver: default-receiver
      routes:
      - match:
          severity: critical
        receiver: default-receiver
      - match: 
          severity: warning
        receiver: default-receiver

    receivers:
    - name: default-receiver
      slack_configs:
        - send_resolved: true
          channel: '#johan-sebastian-bachlava'
          text: '{{ template "slack.default.text" . }}'
          title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"